openapi: 3.1.0
x-stoplight:
  id: 2dw2aket3heib
info:
  title: aesdrftg
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: |-
        new The beginning of an awesome article...



        https://test123.x-20398.stoplight-dev.com/docs/spectral/docs/reference/openapi-rules.md#info-description

        https://test123.x-20398.stoplight-dev.com/docs/spectral/docs/reference/openapi-rules.md#operation-tags

        Check below rules https://test123.x-20398.stoplight-dev.com/docs/spectral/docs/reference/openapi-rules.md#info-contact

        https://test123.x-20398.stoplight-dev.com/docs/spectral/docs/reference/openapi-rules.md#info-description

        https://test123.x-20398.stoplight-dev.com/docs/spectral/docs/reference/openapi-rules.md#operation-tags

        https://test123.x-20398.stoplight-dev.com/docs/spectral/docs/reference/openapi-rules.md#operation-operationid-unique

        https://test123.x-20398.stoplight-dev.com/docs/spectral/docs/reference/arazzo-rules.md#arazzo-workflowid-unique

        https://test123.x-20398.stoplight-dev.com/docs/spectral/docs/reference/error-handling.md#rulesets

        Few more https://test123.x-20398.stoplight-dev.com/docs/spectral/docs/migration-guides/5.0.md#i-use-spectral-programmatically-via-api

        Check from Project name -check-other-files-2630 https://test123.x-20398.stoplight-dev.com/docs/check-2630/docs/mdu.md#pizza

        https://test123.x-20398.stoplight-dev.com/docs/check-2630/docs/mdu.md#PIZZA

        https://test123.x-20398.stoplight-dev.com/docs/check-2630/docs/mdu.md#PIZZA-1

        https://test123.x-20398.stoplight-dev.com/docs/check-2630/docs/mdu.md#pizza-1

        https://test123.x-20398.stoplight-dev.com/docs/check-2630/docs/mdu.md#license-url

        https://test123.x-20398.stoplight-dev.com/docs/check-2630/docs/mdu.md#info-license

        https://test123.x-20398.stoplight-dev.com/docs/check-2630/docs/mdu.md#info-description

        Check For New Version Check from Project name -check-other-files-2630 https://test123.x-20398.stoplight-dev.com/docs/check-2630/branches/new/docs/mdu.md#pizza

        https://test123.x-20398.stoplight-dev.com/docs/check-2630/branches/new/docs/mdu.md#pizza

        https://test123.x-20398.stoplight-dev.com/docs/check-2630/branches/new/docs/mdu.md#license-url

        https://test123.x-20398.stoplight-dev.com/docs/check-2630/branches/new/docs/mdu.md#info-license

        https://test123.x-20398.stoplight-dev.com/docs/check-2630/branches/new/docs/mdu.md#info-description
      x-stoplight:
        id: rs8jmfzvffbsl
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
      x-stoplight:
        id: brh1eujw6vvm5
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: nu6xgkk3j1s1s
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: y5gc7kkvzvm3p
        firstName:
          type: string
          x-stoplight:
            id: 8sw2lk41t7btx
        lastName:
          type: string
          x-stoplight:
            id: afmw75c7nkary
        email:
          type: string
          format: email
          x-stoplight:
            id: 0nhy4empzmgp2
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: 4t9zutjk85fop
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: i3s99vevo3n0y
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: 10d9uei3yc241
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: ywzj92t1zaa1c
